### ISSUE TITLE
Restructuring branch

### ISSUE THREAD

**Issue by cbojar** [rikai/Showbot#28]
Ok so maybe there is something I don't know then. What is the Restructuring branch for?

**Comment by rikai** [comment]
Technically it's not NEEDED, but it's attached to [this pr](https://github.com/mutewinter/Showbot/pull/55) for upstream. Don't see the harm in leaving it there in case upstream ever decides to resume their fork of the project.

**Comment by rikai** [comment]
Just an update, that this banch is now deleted, since i got around to merging the PR upstream.
