### ISSUE TITLE
Don't fail if quotes file does not exist.

### ISSUE THREAD

**Issue by rikai** [rikai/Showbot#65]
Currently the bot fails to start if there's no quotes.yml.

Instead,we should either create a skeleton file if none exists or just not create a file until a quote is added.

**Comment by herbmillerjr** [comment]
Anybody running with this one? If not, I'll knock it out for my first crack at things.

**Comment by herbmillerjr** [comment]
What kind of skeleton file are you looking for here? One with actual values like quotes.yml.example or just an empty file (as if we just did `touch quotes.yml`) perhaps with a comment in it explaining what to do with it?

**Comment by s0ph0s-2** [comment]
I introduced this bug, but I've gotten significantly busier lately and have very little time to fiddle with this. Go ahead and take it!

**Comment by s0ph0s-2** [comment]
@herbmillerjr Copying quotes.yml.example sounds like a great solution, but what happens if *that* file doesn't exist? It might be better to just create a blank YAML file to store stuff in.

**Comment by herbmillerjr** [comment]
Mmm... actually I was just making a comparison to the example file, not suggesting copying it (for that very reason). Okay, blank it is.

**Comment by rikai** [comment]
Fixed by #69
