### ISSUE TITLE
Timezone info needs to be updated

### ISSUE THREAD

**Issue by archlinuxrussian** [rikai/Showbot#74]
The timezone info for at least Asia/Pyongyang is off (should be UTC+8:30 instead of UTC+9:00). I am not sure how many other timezones have changed or are off.

**Comment by rikai** [comment]
tzinfo-data probably just needs to be updated. Will get around to this when i'm less sick. Thanks for the report.

**Comment by Xmetalfanx** [comment]
(off topic) hope your not coming down with what Noah had ... anyway hope your feeling better soon

**Comment by ioangogo** [comment]
(off topic)(Not rikai) @Xmetalfanx More than likely at this time of year

Hope you get better @rikai

**Comment by rikai** [comment]
This is an deployment issue and not a bug, so closing this now.
