### ISSUE TITLE
Setting up Showbot in a new environment throws locale error

### ISSUE THREAD

**Issue by thefirstofthe300** [rikai/Showbot#94]
Run from a freshly cloned and installed environement following the steps outlined in the README:

thefirstofthe300:~/workspace (devel) $ foreman run rake db:migrate
rake aborted!
I18n::InvalidLocale: nil is not a valid locale
/usr/local/rvm/gems/ruby-2.1.2/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
/usr/local/rvm/gems/ruby-2.1.2/gems/i18n-0.7.0/lib/i18n/config.rb:34:in `default_locale='
/home/ubuntu/workspace/environment.rb:21:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1411:in `configure'
/usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1981:in `block (2 levels) in delegate'
/home/ubuntu/workspace/environment.rb:15:in `<top (required)>'
/home/ubuntu/workspace/Rakefile:63:in `require'
/home/ubuntu/workspace/Rakefile:63:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by rikai** [comment]
https://github.com/rikai/Showbot/blob/master/.env.example#L4-L6

**Comment by rikai** [comment]
This is documented [here](https://github.com/rikai/Showbot#configuring-jbot)

**Comment by thefirstofthe300** [comment]
Ignore the dummy in the corner...
